<Project Sdk="Aspire.AppHost.Sdk/13.0.0">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<UserSecretsId>littleShop-secrets-id</UserSecretsId>
		<OutputType>Exe</OutputType>
	</PropertyGroup>

	<ItemGroup>
		<!-- Paquetes del orquestador (Versiones gestionadas por Directory.Packages.props) -->
		<PackageReference Include="Aspire.Hosting.AppHost" />
		<PackageReference Include="Aspire.Hosting.PostgreSQL" />
		<PackageReference Include="Aspire.Hosting.Redis" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" />
		<!-- Referencias a tus microservicios -->
		<ProjectReference Include="..\littleShop.identity\littleShop.identity.csproj" />
		<ProjectReference Include="..\littleshop.apiGateway\littleshop.apiGateway.csproj" />
		<ProjectReference Include="..\littleshop.frontend\littleshop.frontend.esproj" />
		
		
	</ItemGroup>

</Project>