<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<InvariantGlobalization>true</InvariantGlobalization>
	  <UserSecretsId>976a6285-1047-4e1a-b3dd-afb7d0091128</UserSecretsId>
  </PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.OpenApi" />
		<PackageReference Include="Microsoft.OpenApi" />
		<PackageReference Include="Scalar.AspNetCore" />

		<PackageReference Include="Aspire.Npgsql.EntityFrameworkCore.PostgreSQL" />
		<PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" />

		<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\littleShop.serviceDefaults\littleShop.serviceDefaults.csproj" />
	</ItemGroup>

</Project>