<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<InvariantGlobalization>true</InvariantGlobalization>
		<GenerateDocumentationFile>false</GenerateDocumentationFile>
		<NoWarn>$(NoWarn);1591</NoWarn>
		  <UserSecretsId>976a6285-1047-4e1a-b3dd-afb7d0091128</UserSecretsId>
	</PropertyGroup>


	<ItemGroup>
		<PackageReference Include="MassTransit.RabbitMQ" />
		<PackageReference Include="Microsoft.AspNetCore.OpenApi" />
		<PackageReference Include="Microsoft.OpenApi" />
		<PackageReference Include="Scalar.AspNetCore" />

		<PackageReference Include="Aspire.Npgsql.EntityFrameworkCore.PostgreSQL" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" />

		<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Relational" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\littleShop.Shared\littleShop.Shared.csproj" />
		<ProjectReference Include="..\littleshop.serviceDefaults\littleshop.serviceDefaults.csproj" />
	</ItemGroup>

</Project>